name: check_python_version

on:
  push:
    branches: [ "main" ]


jobs:
  
  check_python:
    name: Check Python Version
    runs-on: ubuntu-latest

    steps:
      - name: python setup
        uses: actions/setup-python@v2
        with: 
           python-version: 3.11

      - name: pip update
        run: python -m pip install --upgrade pip

   
      - name: Display Python version
        run: python --version
